### ISSUE TITLE
while 문

### ISSUE THREAD

**Issue by iwyoo** [yaksok/yaksok#7]
비슷한 종류의 이슈가 있어서 확인해보았는데,
일반적으로 다른 프로그래밍 언어에 존재하는 while문이 없는 것 같습니다.
물론 무한반복문은 존재하고 이를 그만과 함께 사용하면 while처럼 사용할 수 있긴 하지만, 
일반적으로 사용하는 while문법을 지원하지 않는 이유가 궁금합니다.
"반복 ~ 이면" 과 같은 while문 유사한 문법을 지원하지 않는 설계상의 이유가 있나요?

**Comment by ipkn** [comment]
특별히 이유가 있는건 아니고 좀더 한글에 가까운 표현을 찾지 못해 미뤄둔 상태입니다.
